/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#adc6ff',
        'primary-container': '#2dd4bf',
        error: '#ba1a1a',
        'on-surface-variant': '#3c4a46',
        'tertiary-container': '#b4c1b9',
        background: '#f8f9ff',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        tertiary: '#55615a',
        'tertiary-fixed': '#d9e6dd',
        'surface-container': '#e5eeff',
        outline: '#6b7a76',
        'on-error': '#ffffff',
        'surface-container-high': '#dce9ff',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#bdcac1',
        'on-primary-fixed-variant': '#005047',
        'outline-variant': '#bacac5',
        'on-secondary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#3e4943',
        'inverse-on-surface': '#eaf1ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-background': '#0b1c30',
        'on-primary-fixed': '#00201c',
        surface: '#f8f9ff',
        'inverse-surface': '#213145',
        'on-tertiary-container': '#444f49',
        'on-secondary-container': '#fefcff',
        'secondary-container': '#2170e4',
        'surface-dim': '#cbdbf5',
        'on-secondary-fixed-variant': '#004395',
        'primary-fixed-dim': '#3cddc7',
        'secondary-fixed': '#d8e2ff',
        secondary: '#0058be',
        'surface-tint': '#006b5f',
        'inverse-primary': '#3cddc7',
        primary: '#006b5f',
        'primary-fixed': '#62fae3',
        'surface-container-low': '#eff4ff',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#00574d',
        'on-tertiary-fixed': '#131e19',
        // Added for status semantics not present in the original DESIGN.md
        // token set (see README v2 changelog).
        warning: '#8a5300',
        'warning-container': '#ffddb3',
        'on-warning-container': '#2c1600',
        'on-warning': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'inner-padding': '1.25rem',
        'card-gap': '1.5rem',
        'gutter-md': '1rem',
        'section-margin': '2.5rem',
        'container-padding': '2rem',
      },
      fontFamily: {
        'label-bold': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'stat-value': ['Hanken Grotesk'],
        'display-lg': ['Hanken Grotesk'],
        'headline-md': ['Hanken Grotesk'],
        'headline-sm': ['Hanken Grotesk'],
        'headline-md-mobile': ['Hanken Grotesk'],
      },
      fontSize: {
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'stat-value': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  // Note: the original design mockups referenced the `forms` and
  // `container-queries` Tailwind CDN plugins, but neither's classes
  // (form-input, @container, etc.) are actually used anywhere in
  // index.html or js/**, so they're intentionally left out here to
  // keep the build dependency-light. Add them back if a future page
  // needs them.
  plugins: [],
};
